### ISSUE TITLE
ITypeDefinition.subTypes() always returns empty list

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/typesystem-ts#26]
Consider RAML
```
#%RAML 1.0
title: Pet shop
version: 1
baseUri: /shop

types:

  Pet:
    properties:
      name: string

  Mammal:
    type: Pet

  Bird:
    type: Pet
    properties:
      wingLength: number
```
then execute following code for it:
```
api.types().filter(function(type){
    return type.name()=="Pet"
}).forEach(function(type){
    console.log("Subtypes of", type.name(), ":");
    type.runtimeDefinition().subTypes().forEach(function(st){
        console.log(st.nameId());
    });
});
```
The resulting list in the console is empty.
