### ISSUE TITLE
Consider being compliant with RAML 0.8 property name placeholders ({*})

### ISSUE THREAD

**Issue by xaka** [raml-org/typesystem-ts#28]
As per RAML 0.8, it's possible for property names for headers to have placeholders (`Name-{*}`):

```
#%RAML 0.8
title: ZEncoder API
version: v2
baseUri: https://app.zencoder.com/api/{version}
/jobs:
  post:
    description: Create a Job
    headers:
      Zencoder-Api-Key:
        displayName: ZEncoder API Key
      x-Zencoder-job-metadata-{*}
```

It'd be helpful if project supported it via feature flag or by default so we don't build extra solution on top of it. Consider it as some kind of backward-compatibility.
