### ISSUE TITLE
Extra properties of examples facet are not validated properly

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/typesystem-ts#38]
Sample:
```yaml

#%RAML 1.0
mediaType: application/json
title: x
types:
  Person:
    type: object
    properties:
      name: string
      lastName: string
    example:
      description: 31
      value:
        name:  "2"
        lastName: "4"

```
the same applies to examples. however annotations are validated in context of examples.

Regards,
Pavel
