### ISSUE TITLE
Type system does not follows to `strict:false` option when validating examples

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/typesystem-ts#39]
Type system does not follows to `strict:false` option when validating examples
```yaml

queryParameters:
          sort?:
            type: string[]
            description: |
              The sort order in the format `property,property[,asc|desc]`. The default sort direction is ascending.
              Can be used multiple times for different properties.
            example:
              strict: false 
              value: ?sort=givenName&sort=surname,asc
```
